### ISSUE TITLE
Add ability to sort list by name

### ISSUE THREAD

**Issue by ImFlizz** [Skymirrh/CompatibilityManager#2]
Currently, you can't sort the exe list so it looks very messy. Adding this would really clean it up, If not possible, maybe just setting default sort as A-Z.

**Comment by nbusseneau** [comment]
Thanks for the suggestion. I'll think about it and see if I can do something this weekend... :)

**Comment by nbusseneau** [comment]
Added default Applications sort by Path in [v1.1.1](https://github.com/Skymirrh/CompatibilityManager/releases/tag/v1.1.1).
