### ISSUE TITLE
Can't apply settings

### ISSUE THREAD

**Issue by Splarkszter** [Skymirrh/CompatibilityManager#4]
I'm having an issue with the stupid AMD drivers making games look blue. Found this app on a forum. But i can't apply the settings. Even running the app with admin permissions does not work.

The button seems to not highlight.

(Also, it seems that not all the .exe or games are there anyway)

![image](https://user-images.githubusercontent.com/90066319/194724086-ebad32c8-71ff-4660-a92e-08d3f1bc6207.png)

**Comment by nbusseneau** [comment]
Hi, on my end the app is still working as intended. What are you trying to do specifically, from the moment you open the app until the moment something is apparently not working?

Just in case, here is how I would suggest you use the app:

- `Add folder` > select a folder where you typically store games (e.g. `C:\GOG Games`).
- Repeat for all your game folders (all your Steam libraries, Epic Games, etc.).
- At this point, a bunch of `.exe` will show up on the left in the list, displayed with a strikethrough ~~like this~~.
- Click on `Disable fullscreen optimizations` on the right.
- Click on `Save selected to registry`.

At this point, everything should be done. If you open `Regedit`, you would see all your newly added `.exe` listed, each with at least the `DISABLEDXMAXIMIZEDWINDOWEDMODE` flag set (it's the fullscreen optimizations one).
